# Generated by Django 4.0.10 on 2023-12-22 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_edited'),
        ('accounts', '0005_remove_customuser_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='posts_liked',
            field=models.ManyToManyField(related_name='liked_by', to='posts.post'),
        ),
    ]
