# serializers.py
from rest_framework import serializers
from .models import Device

class DeviceSerializer(serializers.ModelSerializer):
    class Meta:
        model = Device
        fields = ['id', 'user', 'uid', 'ip_address', 'is_online']
        read_only_fields = ['id']  # The ID is automatically generated by Django
